In [2]:
import numpy as np
import matplotlib.pyplot as plt
from cellpose import models, io, metrics
from cellpose.io import imread
import os

In [2]:
def get_filename(filename):
    filename_with_ex = os.path.basename(filename).replace(':', '_').replace('\\', '_').replace('/', '_').replace('?', '_').replace('*', '_').replace('[', '_').replace(']', '_')
    filename_clear = os.path.splitext(filename_with_ex)[0]
    filename_clear = filename_clear[:9]
    return filename_clear

In [3]:
# Load mask_true and mask_pred
filepath_mask_true = "C:/Users/14495/OneDrive - KTH/test data/mask_true"
filepath_mask_pred = "C:/Users/14495/OneDrive - KTH/HepG2_cells results"

files_mask_true = io.get_image_files(filepath_mask_true,"_mask_true.tif")

# Extract image names from mask_true names
filenames_for_filtering = [filepath_mask_pred +'/'+ get_filename(f) for f in files_mask_true]
# Get the corresponding mask_pred names
files_mask_pred,_ = io.get_label_files(filenames_for_filtering, "_cp_masks")

In [5]:
print(files_mask_pred)

['C:/Users/14495/OneDrive - KTH/HepG2_cells results/B2_01_3_1_cp_masks.tif', 'C:/Users/14495/OneDrive - KTH/HepG2_cells results/B2_01_3_2_cp_masks.tif', 'C:/Users/14495/OneDrive - KTH/HepG2_cells results/B2_01_3_3_cp_masks.tif']


In [5]:
# Read the mask files
mask_true = [imread(f) for f in files_mask_true]
mask_pred = [imread(f) for f in files_mask_pred]

In [ ]:
binary_masks = []
for mask in mask_pred:
    binary_mask = mask.copy()
    binary_mask[binary_mask > 0] = 255
    binary_masks.append(binary_mask)

In [7]:
ap, tp, fp, fn = metrics.average_precision(mask_true, mask_pred, threshold = [0.5,0.7])

In [8]:
print(ap)
print(fp)
print(tp)
print(fn)

[[0. 0.]
 [0. 0.]
 [1. 1.]]
[[130. 130.]
 [148. 148.]
 [  0.   0.]]
[[ 0.  0.]
 [ 0.  0.]
 [79. 79.]]
[[255. 255.]
 [255. 255.]
 [  0.   0.]]


In [9]:
AJI = metrics.aggregated_jaccard_index(mask_true, mask_pred)
print(AJI)

[0.01022397 0.01674282 1.        ]


In [15]:
scales = [0.5]
precision, recall, f_score = metrics.boundary_scores(mask_true, mask_pred,scales)
for i, scale in enumerate(scales):
    print(f"Scale: {scale}")
    print(f"Precision: {np.mean(precision[i]):.2f}")
    print(f"Recall: {np.mean(recall[i]):.2f}")
    print(f"F-score: {np.mean(fscore[i]):.2f}\n")

Scale: 0.5
Precision: 0.50
Recall: 1.00


NameError: name 'fscore' is not defined

In [10]:
filepath_true = "C:/Users/14495/OneDrive - KTH/test data/mask_true/B2_01_3_1_cp_masks_true.tif"
filepath_pred = "C:/Users/14495/OneDrive - KTH/test data/mask_true/B2_01_3_1_cp_masks_true.tif"
#filepath_pred = "C:/Users/14495/OneDrive - KTH/test data/HepG2 cells binary results/B2_01_3_1_cp_masks.tif"

In [11]:
mask_true = imread(filepath_true)
mask_pred = imread(filepath_pred)

In [12]:
print(np.unique(mask_true))

[  0 255]


In [13]:
from sklearn.metrics import jaccard_score
ji = jaccard_score(mask_true, mask_pred, average = 'micro')
print(ji)

1.0
